"""deleted tasks

Revision ID: 9914625a131b
Revises: 01ce2093318a
Create Date: 2025-07-09 09:42:49.074764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9914625a131b'
down_revision = '01ce2093318a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.alter_column('note',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_entries_category_id_categories'), 'categories', ['category_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_entries_category_id_categories'), type_='foreignkey')
        batch_op.alter_column('note',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('category_id')

    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
